services:
  nginx:
    image: nginx:alpine
    container_name: rune-egine-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - rune-net

  redis:
    image: redis:alpine
    container_name: rune-engine-redis
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    networks:
      - rune-net

  backend:
    build: ./backend
    container_name: rune-engine-api
    env_file: ./backend/.env
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    networks:
      - rune-net

  frontend:
    build: ./frontend
    container_name: rune-engine-web
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - rune-net

networks:
  rune-net:
    driver: bridge
